spring:
  application:
    name: "escooter-rental"

  datasource:
    url: jdbc:postgresql://localhost:5432/scooter_rental
    username: postgres
    password: Password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    online_store: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/app.log

token:
  signing:
    key: 7C2F6A4D9B1E5F3A8D7C4E6B2A1D5F374C8E9A2D6F5B3C7E1A4D9F2B6C8E5